version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_events
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  eventsapp:
    image: nourxgh/eventsproject:1.0.0
    container_name: events_project
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/events_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
