global:
  scrape_interval: 5s          # frÃ©quence de scrap des mÃ©triques
  evaluation_interval: 5s      # frÃ©quence d'Ã©valuation des rÃ¨gles

scrape_configs:

  # ğŸŒ± Spring Boot app (EventsProject)
  - job_name: 'events_app'
    metrics_path: '/events/actuator/prometheus'
    static_configs:
      - targets: ['app:8089']
        labels:
          application: 'events-project'

  # ğŸ“¦ cAdvisor : mÃ©triques des conteneurs Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # ğŸ–¥ï¸ Node-exporter : mÃ©triques de la VM / host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # ğŸ§  Prometheus lui-mÃªme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
