global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # Scrape Spring Boot app (actuator prometheus)
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8089']

  # Scrape cAdvisor (métriques des containers)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape node-exporter (métriques de la VM / host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
